### PR TITLE
Hbase2

### PR DESCRIPTION
**Pull request by pranny**
First Cut of HBase. Branched off from gem-octocore. Provides HBase ORM.

TODOs
- Rake tasks
- Complete testing

### CODE REVIEW

**Comment by ravingupta** [comment]
@pranny Please update the config repo so that we can create connection with hbase and try run it.

**Comment by pranny** [comment]
@ravingupta updated. kindly check.

**Comment by ravingupta** [comment]
@pranny not able to view the changes in config repo (in both local as well master branch). Please update

**Comment by ravingupta** [comment]
@pranny you also need to add a hbase adapter in octoMessageAdapters please do that also to complete the hbase implementation

**Comment by pranny** [comment]
my bad. I updated in the master branch. Here it goes in the apt branch https://github.com/octoai/config/commit/0a4904577c661ec9e52b40dd151c31231e8b5276

**Comment by pranny** [comment]
@ravingupta The current hbase adapter is not complete from my pov. It has a bunch of untested changes, migrations pending and maybe a few more hiccups. It was supposed to be a first cut supporting only basic ORM. I am working on the cassandra gem now. Will pick it up as soon as I am done there.

**Pull request merged**
